#!/bin/sh -v

rm -rf ~/.vim*

ln -sf $PWD/vimrc ~/.vimrc
ln -sf $PWD/gvimrc ~/.gvimrc

mkdir -p ~/.vim/tmp/backup
mkdir -p ~/.vim/tmp/swap

ln -sf $PWD/vimrc.d ~/.vim/vimrc.d
ln -sf $PWD/UltiSnips ~/.vim/UltiSnips

#git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
#vim +PluginInstall +qall

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
	https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall
